src/main/java/com/portalgonet/entity/Users.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.portalgonet.entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author solit_000
 */
@Entity
@Table(name = "users")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Users.findAll", query = "SELECT u FROM Users u"),
    @NamedQuery(name = "Users.findByIdUser", query = "SELECT u FROM Users u WHERE u.idUser = :idUser"),
    @NamedQuery(name = "Users.findByEmail", query = "SELECT u FROM Users u WHERE u.email = :email"),
    @NamedQuery(name = "Users.findByProvider", query = "SELECT u FROM Users u WHERE u.provider = :provider"),
    @NamedQuery(name = "Users.findByUid", query = "SELECT u FROM Users u WHERE u.uid = :uid"),
    @NamedQuery(name = "Users.findByNameUser", query = "SELECT u FROM Users u WHERE u.nameUser = :nameUser"),
    @NamedQuery(name = "Users.findByCreatedAt", query = "SELECT u FROM Users u WHERE u.createdAt = :createdAt"),
    @NamedQuery(name = "Users.findByUpdateAt", query = "SELECT u FROM Users u WHERE u.updateAt = :updateAt"),
    @NamedQuery(name = "Users.findByPicture", query = "SELECT u FROM Users u WHERE u.picture = :picture"),
    @NamedQuery(name = "Users.findByRole", query = "SELECT u FROM Users u WHERE u.role = :role"),
    @NamedQuery(name = "Users.findByPassword", query = "SELECT u FROM Users u WHERE u.password = :password")})
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "idUser")
    private Integer idUser;
    // @Pattern(regexp="[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", message="Invalid email")//if the field contains email address consider using this annotation to enforce field validation
    @Size(max = 250)
    @Column(name = "email")
    private String email;
    @Size(max = 250)
    @Column(name = "provider")
    private String provider;
    @Size(max = 250)
    @Column(name = "uid")
    private String uid;
    @Size(max = 250)
    @Column(name = "nameUser")
    private String nameUser;
    @Basic(optional = false)
    @NotNull
    @Column(name = "createdAt")
    @Temporal(TemporalType.TIMESTAMP)
    private Date createdAt;
    @Basic(optional = false)
    @NotNull
    @Column(name = "updateAt")
    @Temporal(TemporalType.TIMESTAMP)
    private Date updateAt;
    @Size(max = 250)
    @Column(name = "picture")
    private String picture;
    @Column(name = "role")
    private Integer role;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 250)
    @Column(name = "password")
    private String password;

    public Users() {
    }

    public Users(Integer idUser) {
        this.idUser = idUser;
    }

    public Users(Integer idUser, Date createdAt, Date updateAt, String password) {
        this.idUser = idUser;
        this.createdAt = createdAt;
        this.updateAt = updateAt;
        this.password = password;
    }

    public Integer getIdUser() {
        return idUser;
    }

    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getNameUser() {
        return nameUser;
    }

    public void setNameUser(String nameUser) {
        this.nameUser = nameUser;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdateAt() {
        return updateAt;
    }

    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    public String getPicture() {
        return picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    public Integer getRole() {
        return role;
    }

    public void setRole(Integer role) {
        this.role = role;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idUser != null ? idUser.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Users)) {
            return false;
        }
        Users other = (Users) object;
        if ((this.idUser == null && other.idUser != null) || (this.idUser != null && !this.idUser.equals(other.idUser))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.portalgonet.entity.Users[ idUser=" + idUser + " ]";
    }
    
}

src/main/java/com/portalgonet/controller/ComentariosController.java
package com.portalgonet.controller;

import com.portalgonet.DAO.ComentariosDAO;
import com.portalgonet.modelo.Comentarios;
import com.portalgonet.modelo.Ideas;
import java.util.List;
import java.util.ListIterator;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name = "Comentarios")
@SessionScoped
public class ComentariosController {

    private List<Comentarios> listaComentarios;
    private  Comentarios comentario= new Comentarios();

    public Comentarios getComentario() 
    {
        return comentario;
    }

    public void setComentario(Comentarios comentario) 
    {
        this.comentario = comentario;
    }
    
    public List<Comentarios> getListarComentarios() 
    {
        
        return listaComentarios;
    }

    public void setListarComentarios(List<Comentarios> listaComentarios) 
    {
        this.listaComentarios = listaComentarios;
    }
    
    public void registrarComentariosBean(int id,int idU) throws Exception
    {
       ComentariosDAO comentaris;
         
        try
        {
            comentaris=new ComentariosDAO();
            comentaris.registrarComentario(comentario, id,idU);
            this.comentario.setDescripcion("");
        }catch(Exception e)
        {
            throw e;
        }
    }
    
    public void listarComentariosBean(int id) throws Exception
    {
        ComentariosDAO Listacomentarios;
        
        try
        {
            Listacomentarios=new ComentariosDAO();
            listaComentarios=Listacomentarios.consultarComentarios(id);  
        }
        catch(Exception e)
        {
            throw e;
        }
    }
    
    public void leerIdComentarios(Ideas idea)
    {
        
    }
    
    public void comparaIds(int idIdea,int idIdeaC) throws Exception
    {
        if(idIdea==idIdeaC)
        {
            listarComentariosBean(idIdea);
        }else
        {     
        }
    }
    
    String i="Mostrar Comentarios";
    int j=0;
    
    public void accionBotonComentar()
    {  
        if(i.equals("Ocultar Comentarios"))
        {
            j=0;
        }
        j=1;
    }
    public String msjBotonComentar()
    {
        if(j==1)
        {
            System.out.println("muestra ocultarcomentario");
            return "Ocultar Comentarios";   
        }
        return "Mostrar Comentarios";
    }
    public int totalComentarios(int id) throws Exception
    {
        int total=0;
        ComentariosDAO comentar=new ComentariosDAO();
        total=comentar.totalDeComentarios(id);
        return total;
    }
    public void listarIdUserComentarioBean(){}
    public void MencionarBean(){}
    public void limpiaComentarios()
    {
        this.comentario.setDescripcion("");
    }

}

src/main/java/com/portalgonet/controller/IdeasController.java
package com.portalgonet.controller;

import com.portalgonet.DAO.IdeasDAO;
import com.portalgonet.modelo.Ideas;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name="IdeaR")
@SessionScoped
public class IdeasController {
    private Ideas idea= new Ideas();
    private List<Ideas> listarIdeas;
    

    public Ideas getIdea() {
        return idea;
    }

    public void setIdea(Ideas idea) {
        this.idea = idea;
    }

    public List<Ideas> getListarIdeas() {
        return listarIdeas;
    }

    public void setListarIdeas(List<Ideas> listarIdeas) {
        this.listarIdeas = listarIdeas;
    }
    
    public void leerIdIdeasBean(Ideas ideas) throws Exception
    {
        IdeasDAO dao;
        Ideas tmp;
        try
        {
            dao=new IdeasDAO();
            tmp=dao.leerId(ideas);
            if(tmp!=null)
            {
                this.idea=ideas;
            }
            
        }catch(Exception e)
        {
            throw e;
        }
    }
    
    public void listar() throws Exception{
        IdeasDAO dao;
    
        try{
            dao = new IdeasDAO();
            listarIdeas = dao.consultarIdea();
        }
        catch(Exception e){
            throw e;
        }
    }
    
    public void leerId(Ideas leerIdea) throws Exception{
        IdeasDAO dao;
        Ideas temp;
        try{
            dao = new IdeasDAO();
            temp = dao.leerId(leerIdea);
            if(temp != null){
                this.idea =temp;
                
            }
        }
        catch(Exception e){
            throw e;
        }
    }
    
    public String visibleInvisible(String imagen)
   {
       if(imagen.equals(""))
       {
           return "display:none;";
       }
       return "";
   }
    
    public void generavalor()
    {
       this.muestra="display:none;";
       System.out.println("el id de la idea seleccionada es: >>"+this.idea.getId());
    }
    
    public void quitavalor()
    {
        this.muestra="display:inline;";
        System.out.println("quitar valor de id: >>"+this.idea.getId());
    }
    public String mostrarInput()
    {
        if(muestra.equals("display:none;")){
        return "display:inline;";
        }
        return "display:none;";
    }
    public String Updateid()
    {
        int id=this.idea.getId();
        if(id>0)
        {
            return "tabdatos2:n";
        }
        return "tabdatos2:p";
    }
    public String idpanel()
    {
      int id=this.idea.getId();
        if(id>0)
        {
            return "n";
        }
        return "p";  
    }
    
    String muestra="";

    public String getMuestra() {
        return muestra;
    }

    public void setMuestra(String muestra) {
        this.muestra = muestra;
    }
    
    public void lipiaPagIdeas() {
        muestra = "";
        botonMostrar = true;
        botonOculatr = false;
        comentariosMostrar = false;
    }

    public String prueba(String titulo) {
        System.out.println("El titulo es:>>>" + titulo + "<<<<<<<<<");
        return titulo;
    }
    private boolean botonMostrar = true;
    private boolean botonOculatr = false;
    private boolean comentariosMostrar = false;

    public void accionBoton() {
        if (botonMostrar) {
            botonMostrar = false;
            botonOculatr = true;
            setComentariosMostrar(true);
        } else {
            botonMostrar = true;
            botonOculatr = false;
            setComentariosMostrar(false);
        }
    }

    /**
     * @return the botonMostrar
     */
    public boolean isBotonMostrar() {
        return botonMostrar;
    }

    /**
     * @param botonMostrar the botonMostrar to set
     */
    public void setBotonMostrar(boolean botonMostrar) {
        this.botonMostrar = botonMostrar;
    }

    /**
     * @return the botonOculatr
     */
    public boolean isBotonOculatr() {
        return botonOculatr;
    }

    /**
     * @param botonOculatr the botonOculatr to set
     */
    public void setBotonOculatr(boolean botonOculatr) {
        this.botonOculatr = botonOculatr;
    }

    /**
     * @return the comentariosMostrar
     */
    public boolean isComentariosMostrar() {
        return comentariosMostrar;
    }

    /**
     * @param comentariosMostrar the comentariosMostrar to set
     */
    public void setComentariosMostrar(boolean comentariosMostrar) {
        this.comentariosMostrar = comentariosMostrar;
    }
    
}

src/main/java/com/portalgonet/controller/LoginController.java
package com.portalgonet.controller;

import com.portalgonet.DAO.LoginDAO;
import com.portalgonet.entity.Users;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name= "loginx")
@SessionScoped
public class LoginController {
    private String nombre;
    private String email;
    private String password;
    private String fotoPerfil;

    private Users u;

    public Users getU() {
        return u;
    }

    public void setU(Users u) {
        this.u = u;
    }
    
    public String getFotoPerfil() {
        return fotoPerfil;
    }

    public void setFotoPerfil(String fotoPerfil) {
        this.fotoPerfil = fotoPerfil;
    }
    
    public String ValidaLogin() throws Exception{
        LoginDAO USER = new LoginDAO();
        u= USER.VlidarUsuario(email,password);
        if(u != null){
            nombre = u.getNameUser();
            fotoPerfil =u.getPicture();
            return "inicio";
        }
        else{
            return"index";
        }
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    
}

src/main/java/com/portalgonet/controller/solicitudDeApoyoController.java
package com.portalgonet.controller;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;


@ViewScoped
@ManagedBean (name="solicitudApoyo")
public class solicitudDeApoyoController {

    
}

src/main/webapp/ReporteDeAutoevaluacionDelOrganismoPromotor.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head/>

    <title>Reporte de autoevaluacion del organismo promotor</title>
    <h:outputStylesheet library="css"  name="formatos.css"/>
    <body>
        <div class="contenidoBody">
            <div id="CabeceraMod">
                <h:form>
                    <p:tabMenu activeIndex="2">
                        <p:menuitem class="colormenu" value="Inicio"  action="inicio" />
                        <p:menuitem class="colormenu" value="Idea" action="ideas"/>
                        <p:menuitem class="colormenu" value="Investigacion" action="investigacion"/>
                        <p:menuitem class="colormenu" value="Prototipo" action="prototipo"/>
                        <p:menuitem class="colormenu" value="Proyecto" action="proyecto"/>
                        <p:menuitem class="colormenu" value="Comercializacion" action="comercializacion"/>
                        <p:menuitem class="colormenu" value="Cerrar sesion"/>
                    </p:tabMenu>
                </h:form>
            </div>
            
             <section id="columnaizquierda">
                <h:form>
                    <h:panelGroup id="imagenperfil">
                        <center><h:outputLabel value="#{loginx.nombre}" /></center>
                        <center><p:graphicImage library="images" name="userdefaul.png" 
                                                title="Usuario1" width="100" height="auto"/></center>
                        <h:form>
                            <center><p:commandLink value="Editar Perfil" onclick="" 
                                                   style="margin-left:10%; font-size:12px; 
                                                   color:white;"/></center> 
                        </h:form>
                    </h:panelGroup>
                </h:form>
            </section>
            
            <section id="contenidocentral">
                <h:form>
                    
                </h:form>
            </section>
            
            <div class="columnaderecha">
            </div>
        </div>
    </body>
</html>

src/main/webapp/ejemploTabla.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head/>

    <title>Investigacion</title>
    <h:outputStylesheet library="css"  name="investigacion.css"/>
    
    <body>
        <p:panelGrid style="margin-top:20px">
            <f:facet name="header">
                <p:row>
                    <p:column colspan="7">1995-96 NBA Playoffs</p:column>
                </p:row>
                <p:row>
                    <p:column colspan="2">Conf. Semifinals</p:column>
                    <p:column colspan="2">Conf. Finals</p:column>
                    <p:column colspan="2">NBA Finals</p:column>
                    <p:column>Champion</p:column>
                </p:row>

            </f:facet>

            <p:row>
                <p:column style="font-weight: bold;">Seattle</p:column>
                <p:column style="font-weight: bold;">4</p:column>

                <p:column rowspan="2" style="font-weight: bold;">Seattle</p:column>
                <p:column rowspan="2" style="font-weight: bold;">4</p:column>

                <p:column rowspan="5">Seattle</p:column>
                <p:column rowspan="5">2</p:column>

                <p:column rowspan="11" style="font-weight: bold;">Chicago</p:column>
            </p:row>

            <p:row>
                <p:column>Houston</p:column>
                <p:column >0</p:column>
            </p:row>

            <p:row>
                <p:column colspan="4" styleClass="ui-widget-header">
                    <p:spacer height="0"/>
                </p:column>
            </p:row>

            <p:row>
                <p:column style="font-weight: bold;">Utah</p:column>
                <p:column style="font-weight: bold;">4</p:column>

                <p:column rowspan="2">Utah</p:column>
                <p:column rowspan="2">3</p:column>
            </p:row>

            <p:row>
                <p:column>San Antonio</p:column>
                <p:column >2</p:column>
            </p:row>

            <p:row>
                <p:column colspan="6" styleClass="ui-widget-header">
                    <p:spacer height="0"/>
                </p:column>
            </p:row>

            <p:row>
                <p:column style="font-weight: bold;">Chicago</p:column>
                <p:column style="font-weight: bold;">4</p:column>

                <p:column rowspan="2" style="font-weight: bold;">Chicago</p:column>
                <p:column rowspan="2" style="font-weight: bold;">4</p:column>

                <p:column rowspan="5" style="font-weight: bold;">Chicago</p:column>
                <p:column rowspan="5" style="font-weight: bold;">4</p:column>
            </p:row>

            <p:row>
                <p:column>New York</p:column>
                <p:column >1</p:column>
            </p:row>

            <p:row>
                <p:column colspan="4" styleClass="ui-widget-header">
                    <p:spacer height="0"/>
                </p:column>
            </p:row>

            <p:row>
                <p:column>Atlanta</p:column>
                <p:column >1</p:column>

                <p:column rowspan="2">Orlando</p:column>
                <p:column rowspan="2">0</p:column>
            </p:row>

            <p:row>
                <p:column style="font-weight: bold;">Orlando</p:column>
                <p:column style="font-weight: bold;">4</p:column>
            </p:row>


            <f:facet name="footer">
                <p:row>
                    <p:column  colspan="4" style="text-align: right">
                        Finals MVP
                    </p:column>
                    <p:column  colspan="3" rowspan="3">
                        Michael Jordan (Chicago)
                    </p:column>
                </p:row>

                <p:row>
                    <p:column  colspan="4" style="text-align: right">
                        Season MVP
                    </p:column>
                </p:row>
                <p:row>
                    <p:column  colspan="4" style="text-align: right">
                        Top Scorer
                    </p:column>
                </p:row>
            </f:facet>
        </p:panelGrid>
    </body>
</html>

src/main/webapp/index.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>Hello World!</h1>
    </body>
</html>

src/main/webapp/inicio.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head/>

    <title>Inicio</title>
    <h:outputStylesheet library="css"  name="Inicio.css"/>

    <body onload="#{IdeaR.listar()} #{IdeaR.lipiaPagIdeas()}">
        <div class="contenidoBody"> 

            <div id="CabeceraIni">
                <h:form>
                    <p:tabMenu activeIndex="0">
                        <p:menuitem class="colormenu" value="Inicio"  action="inicio" />
                        <p:menuitem class="colormenu" value="Idea" action="ideas"/>
                        <p:menuitem class="colormenu" value="Investigacion" action="investigacion"/>
                        <p:menuitem class="colormenu" value="Prototipo" action="prototipo"/>
                        <p:menuitem class="colormenu" value="Proyecto" action="proyecto"/>
                        <p:menuitem class="colormenu" value="Comercializacion" action="comercializacion"/>
                        <p:menuitem class="colormenu" value="Cerrar sesion"/>
                    </p:tabMenu>
                </h:form>
            </div>

            <section id="columnaizquierda">
                <h:form>
                    <h:panelGroup id="imagenperfil">
                        <center><h:outputLabel value="Bienvenido al Portal: #{loginx.nombre}" /></center>
                        <center><p:graphicImage library="images" name="userdefaul.png"  title="Usuario1" width="100" height="auto"/></center>
                        <h:form>
                            <center><p:commandLink value="Editar Perfil" onclick="" style="margin-left:10%; font-size:12px; color:white;"/></center> 
                        </h:form>
                    </h:panelGroup>
                </h:form> 
            </section>

            <section id="contenidocentral">
                <p:growl id="mensaje2"/>
                <h:panelGroup id="publicaciones">

                    <p:dataList value="#{IdeaR.listarIdeas}" var="datos" id="tabdatos2" type="definition" emptyMessage="No hay Datos">
                        <p:panel header="#{datos.titulo}" style="margin-top:4%;" closable="4">

                            <p:panelGrid style="width:auto;">
                                <p:outputLabel value="Descripcion:" style="font-size:150%;"/>                                
                                <section class="seccion">
                                    <p:lightBox class="imagenBox">
                                        <h:outputLink value="../imagenes/#{datos.imagen}" title="Imagen: #{datos.imagen}">
                                            <h:graphicImage  value="/imagenes/#{datos.imagen}" style=" #{IdeaR.visibleInvisible(datos.imagen)}"/>
                                        </h:outputLink>
                                    </p:lightBox>
                                    <p><p:outputLabel  value="#{datos.descripcion}"/></p>
                                </section>
                            </p:panelGrid>

                            <h:form id="btnf1">
                                <p:panelGrid layout="grid" columns="4">
                                    <p:commandButton id="MeGusta" value="Me Gusta"/>
                                    <p:commandButton id="Favorito" value="Agrgar a Favoritos"/>
                                    <p:commandButton id="Comentar"  value="Comentarios (#{Comentarios.totalComentarios(datos.id)})" actionListener="#{IdeaR.leerIdIdeasBean(datos)}" 
                                                     oncomplete="#{ComentariosBean.listarComentariosBean(datos.id)}" styleClass="#{datos.id}" style="#{IdeaR.muestra}"  
                                                     action="#{IdeaR.generavalor()}" update="@(.#{datos.id})"/>
                                    <p:commandButton id="modifica" value="Modificar" actionListener="#{IdeaR.leerIdIdeasBean(datos)}" 
                                                     oncomplete="PF('wdialogDatos').show();"/>
                                </p:panelGrid>
                            </h:form>

                            <p:outputLabel value="Fecha de Creación: #{datos.creacion}" style="font-size:15px; margin-right:auto;"/> <br/>
                            <p:outputLabel value="Ultima Actualización: #{datos.actualizacion}" style="font-size:15px; margin-right:auto;"/><br/>

                            <h:form id="btnsform2">
                                <p:panelGrid id="comentt">
                                    <p:inputTextarea value="#{Comentarios.comentario.descripcion}" styleClass="#{datos.id}" style="width:50%;" placeholder="Comentar!!" rows="2"/>
                                    <p:commandButton  value="Comentar" action="#{IdeaR.quitavalor()}" actionListener="#{Comentarios.registrarComentariosBean(datos.id,loginx.u.idUser)}" 
                                                      oncomplete="#{Comentarios.limpiaComentarios()}" update="@(.#{datos.id})"/><br/>
                                    <p:commandLink styleClass="#{datos.id}"  value="Mostrar Comentarios: " rendered="#{IdeaR.botonMostrar}" 
                                                   actionListener="#{IdeaR.accionBoton()}" update="btnsform2,@(.#{datos.id})"/>
                                    <p:commandLink styleClass="#{datos.id}"  id="OcultarComent" value="Ocultar Comentarios" rendered="#{IdeaR.botonOculatr}" 
                                                   actionListener="#{IdeaR.accionBoton()}" update="btnsform2,@(.#{datos.id})"/>
                                    <span class="badge" onload="#{ComentariosBean.listarComentariosBean(datos.id)}"><h:panelGroup styleClass="#{datos.id}">#{Comentarios.totalComentarios(datos.id)}</h:panelGroup></span>
                                </p:panelGrid>
                            </h:form ><br/>

                            <h:form id="btnform3"  styleClass="#{datos.id}">
                                <p:dataList rendered="#{IdeaR.comentariosMostrar}" id="lsi"  value="#{Comentarios.listarComentarios}" var="comentDato" 
                                            type="definition" emptyMessage="No hay Comentarios!!" styleClass="#{datos.id}">
                                    <p:panel>
                                        <p:panelGrid>
                                            <p:outputLabel value="Id de Usuario: #{comentDato.idUser}" style="font-size:16px;"/>
                                            <div id="seccionactcrea">
                                                <p:outputLabel value="#{comentDato.creacion}" style="font-size:9px;"/><br/>
                                                <p:outputLabel value="#{comentDato.actualizacion}" style="font-size:9px;"/>
                                            </div>
                                            <section class="seccion">
                                                <p><p:outputLabel value="#{comentDato.descripcion}"/></p>
                                            </section>
                                            <p:inputTextarea value="#{Comentarios.comentario.descripcion}"  style="width:50%" placeholder="Responder!!" rows="1"/>
                                            <p:commandButton value="Responder" action="#{IdeaR.quitavalor()}" update="@(.#{datos.id})"/>
                                        </p:panelGrid>
                                    </p:panel>
                                    <div class="separador"></div>
                                </p:dataList>
                            </h:form>

                        </p:panel>
                    </p:dataList>
                </h:panelGroup>
            </section>

            <div class="columnaderecha">
            </div>

        </div>
    </body>
</html>